database:
  host: 112.74.200.88
  #host: 10.10.80.14
  port: 3306
  databasename: netx
  username: wz
  #username: netx
  password: WzJh6612520
  #password: 123
oss:
  #bucket-name: wzprojectbucket
  bucket-prefix: netx-dev
#upload:
#  imgPre: img-dev-
jiguang:
  app-key: f08f0f1afc3104253d3b29e9
  secret: 5e675410ac12e6fc149044d9
jwt:
  header: Token
  expires_in: 86400000 # 24 小时
  mobile_expires_in: 86400000 # 24 小时
  secret: iukjytrqzdlq
admin:
  ip: 127.0.0.1
  port: 8083