database:
  host: 112.74.200.88
  port: 3306
  databasename: netx
  username: wz
  password: WzJh6612520
jwt:
  header: Token
  expires_in: 86400000 # 24 小时
  mobile_expires_in: 86400000 # 24 小时
  secret: iukjytrqzdlq
jiguang:
  app-key: f08f0f1afc3104253d3b29e9
  secret: 5e675410ac12e6fc149044d9
oss:
  #bucket-name: wzproject-prod
  bucket-prefix: netx
